apiVersion: v1
kind: Service
metadata:
  labels:
    app: mydeployment
  name: mydeployment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mydeployment
  type: NodePort

